tasks:
  - name: terraform
    before: |
        cd $PROJECT_ROOT
        source ./bin/alias-tf.sh
        source ./bin/install-terraform-cli.sh 
        source ./bin/generate-tfrc-token.sh
        cp $PROJECT_ROOT/terraform.tfvars.example  $PROJECT_ROOT/terraform.tfvars
  - name: sinatra
    before: | 
      cd $PROJECT_ROOT
      bundle install
      bundle exec ruby server.rb       
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
        cd $PROJECT_ROOT
        source ./bin/install-aws-cli.sh
        source ./bin/alias-tf.sh
  - name: http-server
    before: |
      cd $PROJECT_ROOT
      npm install --global http-server
    command: 
      http-server
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform