tasks:
  - name: terraform
    before: |
        source ./alias-tf.sh
        source ./bin/install-terraform-cli.sh 
        source ./bin/generate-tfrc-token.sh
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
        source ./bin/install-aws-cli.sh
        source ./alias-tf.sh
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform